

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_NYC_PROJECT
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60          
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database + schémas (équivalent Bronze/Silver/Gold en dbt = staging/intermediate/marts)
CREATE DATABASE IF NOT EXISTS NYC_PROJECT;
CREATE SCHEMA IF NOT EXISTS NYC_PROJECT.RAW;         
CREATE SCHEMA IF NOT EXISTS NYC_PROJECT.STAGING;    
CREATE SCHEMA IF NOT EXISTS NYC_PROJECT.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NYC_PROJECT.MARTS;       

CREATE ROLE IF NOT EXISTS ROLE_NYC_PROJECT;

GRANT USAGE ON WAREHOUSE WH_NYC_PROJECT TO ROLE ROLE_NYC_PROJECT;
GRANT USAGE ON DATABASE NYC_PROJECT TO ROLE ROLE_NYC_PROJECT;
GRANT ALL ON SCHEMA NYC_PROJECT.RAW TO ROLE ROLE_NYC_PROJECT;
GRANT ALL ON SCHEMA NYC_PROJECT.STAGING TO ROLE ROLE_NYC_PROJECT;
GRANT ALL ON SCHEMA NYC_PROJECT.INTERMEDIATE TO ROLE ROLE_NYC_PROJECT;
GRANT ALL ON SCHEMA NYC_PROJECT.MARTS TO ROLE ROLE_NYC_PROJECT;

CREATE ROLE IF NOT EXISTS ROLE_AGENT_READONLY;
GRANT USAGE ON WAREHOUSE WH_NYC_PROJECT TO ROLE ROLE_AGENT_READONLY;
GRANT USAGE ON DATABASE NYC_PROJECT TO ROLE ROLE_AGENT_READONLY;
GRANT USAGE ON SCHEMA NYC_PROJECT.MARTS TO ROLE ROLE_AGENT_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA NYC_PROJECT.MARTS TO ROLE ROLE_AGENT_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NYC_PROJECT.MARTS TO ROLE ROLE_AGENT_READONLY;

GRANT ROLE ROLE_NYC_PROJECT TO USER <USER>;
GRANT ROLE ROLE_AGENT_READONLY TO USER <USER>;

